### ISSUE TITLE
NodeSchool International Day

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#1]
cc: @switters @slajax

Hi, I see that [NodeSchool International Day](http://nodeschool.io/international-day/) is coming up on **May 23rd**. Would anyone be into organizing an event here in Vancouver? I'd love to help out, and we have some space at the new Zillow office in Yaletown to host.

**Comment by Qard** [comment]
@sintaxi Care to comment?

I've already got DanceJS happening that evening, and Brock was planning a NodeSchool and Node Brigade for that day anyway, might as well connect it to that. :)

**Comment by lvivier** [comment]
@Qard hey I chatted with @sintaxi last week and he likes the idea of connecting up all three. I'm gonna  move forward with the idea of doing nodeschool here at Zillow.

**Comment by adriandgr** [comment]
I like this idea! (Just starting out JS)

**Comment by lvivier** [comment]
@sintaxi @adriandgr @Qard 

I've added the event on Tito:

https://ti.to/nodeschool-vancouver/2015-05-23

Please sign up if you want to attend as either a student or mentor, I'll have some more info as we get closer to the date.

**Comment by Qard** [comment]
I'm in for sure. Thanks for the heads up! :)

**Comment by superkhau** [comment]
wow its already full

**Comment by kennethormandy** [comment]
On that subject, I sent this to my classmates at Emily Carr University and there was a really enthusiastic response, I think some of them still didn’t get a ticket though (including me!) If there’s any possibility to move it to a larger venue, I think there’s enough interest to accommodate it. /cc @sintaxi

**Comment by superkhau** [comment]
:+1:

**Comment by Qard** [comment]
+1 on a bigger venue. Do we have enough extra mentors to handle a bigger scale though?

**Comment by lvivier** [comment]
@kennethormandy I just added 10 more student tickets, we're gonna buy some extra chairs! If that fills up too we'll have to look to a bigger venue. I'll press gang some of our guys into mentoring :D

**Comment by sintaxi** [comment]
We can do two venues. We can host here at Chloi HQ.

**Comment by gyaresu** [comment]
:+1: New to Van. Definitely attending. Wherever that may end up.

Just a heads-up:
I put down as 'mentor'. While I'm still heavily in learning-mode myself I definitely know enough to help others and I do like to teach.

https://github.com/gyaresu/nodeschool

**Comment by highestblue** [comment]
I just got started with node.js. Looking forward to joining the event, and meeting some node.js gurus :)

**Comment by superkhau** [comment]
I put down mentor too. Look forward to seeing some of you guys there. ;)

**Comment by rdswanson** [comment]
Dang, missed the registration for students twice now! I'll keep a closer watch to see if anything opens up.

**Comment by theShifting** [comment]
Same here!

**Comment by amatecha** [comment]
Dang, missed as well, but I'm glad we have a local nodeschool chapter.   Next time, I guess!

**Comment by alololox** [comment]
Missed out. Will keep my eyes peeled for the next one!

**Comment by gyaresu** [comment]
@lvivier  @sintaxi  I’m eager to sort out a final list of actual attendees, open vacated spots and ensure all dev machines have required implementations of Node prior to Saturday.

**Comment by gyaresu** [comment]
One space free already @amatecha @alololox @rdswanson @theShifting

**Comment by gyaresu** [comment]
Notes for the day: https://gist.github.com/gyaresu/1848acc320e4c441d995

Registration page: https://ti.to/nodeschool-vancouver/2015-05-23

**Comment by ragavendra** [comment]
hey guys,
 what time exactly is the event? I remember it was noonish. Do you think I should get my laptop?

**Comment by gyaresu** [comment]
Ragavendra!

Hi! Your email address bounced when I sent the notification. 

I'll forward to you now. Don't worry if your laptop is not set up yet we'll sort it there. 

See you a bit later :)

---

Gareth

Crypto: https://keybase.io/gyaresu

[Sent via magical thumb-typing  pocket computing device]

**Comment by gyaresu** [comment]
Ah. I got that last response as a GitHub email. ;)

Just click the links I posted above @ragavendra and all will be revealed!

**Comment by lvivier** [comment]
Thanks for coming, everyone! Special thanks to all our mentors. It was a big success, we'll announce the next one soon.

@RongxinZhang can you link to images/video here when they're ready?
