### ISSUE TITLE
Link to URL should be in repo. 

### ISSUE THREAD

**Issue by tomkf** [nodeschool/vancouver#103]
Please provide the URL!
(in README/Description)

**Comment by halkeye** [comment]
Url to what? Where?

**Comment by tomkf** [comment]
https://nodeschool.io/vancouver/

**Comment by keywordnew** [comment]
@tomkf do you think we can mark this with a good-first-issue label? Or would you prefer to make a PR with the edits yourself in the location that the URL seems necessary. I'm happy to review it myself.

https://github.com/nodeschool/vancouver/edit/master/README.md

**Comment by tomkf** [comment]
Hi there, I included my changes. 

Also if the link could be included in the repository description like they have on the flagship repo:
![Screen Shot 2019-08-02 at 11 09 57 PM](https://user-images.githubusercontent.com/26214634/62406782-bc3afd00-b57e-11e9-8c00-757dedc07af7.png)

**Comment by keywordnew** [comment]
Thanks @tomkf.

<img width="615" alt="Screen Shot 2019-08-02 at 9 59 05 PM" src="https://user-images.githubusercontent.com/10335475/62407669-1af97a00-b571-11e9-9be7-d8a2e2eecf0e.png">

**Comment by halkeye** [comment]
I closed it because I thought it was done, but I also see the PR got closed, so I'm confused. Please reopen if you feel like it still needs doing.
