### ISSUE TITLE
Add "sign up to be notified of new events"

### ISSUE THREAD

**Issue by bmann** [nodeschool/vancouver#12]
This is available via Tito.

The Ull page has code to be used as an example -- http://2015.ull.ie/

The JS is pasted below. Somebody want to make a no Jquery version?

BTW -- this is actually tied to individual events, so I guess we just use the original Intl Day event for now, if we decide to go this route.

```
jQuery.fn.shake = function(amount){
  $(this).velocity('callout.shake')
}

jQuery(function(){
  var callback
  $('.register-interest-form').submit(function(){
    name  = $('#register-name').val()
    email = $('#register-email').val()
    if($.trim(name) != '' && $.trim(email) != '')
    {
      url = ["https://ti.to/ull/2015/interested_users/subscribe.json?&interested_user[email]=", email , "&interested_user[name]=", name, "&callback=?"].join('')
      $.getJSON(url, null, function(data){})
      width = $('.register-interest-form').width()
      height = $('.register-interest-form').height()
      $('.register-interest-form')
        .velocity({rotateY: 10, rotateX: 0})
        .velocity({x: 1900}, 200, 'linear')
        .velocity({opacity: 0, x: 3000}, 100, 'linear')
        .promise().done(function(){
        $('.register-interest-form').html(['<h2 class="thanks">', 'Thanks ', name.split(' ')[0], '</h2>'].join(''))
        $('.register-interest-form').velocity({
          x: 0, y: 0, rotateY: 0, rotateX: 0, width: width, height: height}, 300, 'linear')
          .velocity({opacity: 1}, 300, 'linear')
      })
    }
    else
    {
      $('.register-interest-form').shake()
    }
    return false;
  })
})
```

**Comment by lvivier** [comment]
@bmann I think in lieu of a mailing list type signup, we should drive people to this repo and encourage them to star/watch it for updates and get involved a bit more. Thoughts?

**Comment by bmann** [comment]
If you only want people who already know GitHub, do this. 

If you want an easier on ramp, do something simpler like a mailing list signup.

**Comment by kennethormandy** [comment]
To echo what Boris said… Last time quite a few designers I had studied with were interested in attending, or did attend. While they wouldn’t have a problem creating a GitHub account and they know it exists, they don’t actively use it so it’s not a great way to reach them. Using GitHub Issues could also mean a lot of noise from the organisation discussions, rather than just an infrequent update email.

**Comment by gyaresu** [comment]
I've created a mailing list: vancouver.nodeschool@librelist.com

I'm a big fan of encouraging it as a notification-only list but true to Open Source style it has no owners and can therefore survive past any individual member.

**Comment by gyaresu** [comment]
Thoughts? Close this issue?

**Comment by bmann** [comment]
@gyaresu cool, nice.

Needs to get added to the website --> http://nodeschool.io/vancouver/

Which also needs edits like "list who main organizers are"

And needs updating to indicate what the next / new events are?

**Comment by gyaresu** [comment]
@bmann Yeah, it's a little convoluted right now.

##### Updates are required on three pages:
- http://nodeschool.io/vancouver // Edited to make @bmann doubt his sanity :)
- https://github.com/nodeschool/vancouver
- https://ti.to/nodeschool-vancouver/
  <hr />

##### The http://nodeschool.io/vancouver website is edited via the `ghpages` branch:
- https://github.com/nodeschool/vancouver/tree/gh-pages

##### The https://github.com/nodeschool/vancouver page is just the README.md for the repo:
- https://github.com/nodeschool/vancouver/blob/master/README.md

##### And https://ti.to/nodeschool-vancouver/ is via any URL + `/admin`
- https://ti.to/nodeschool-vancouver/admin

**Comment by bmann** [comment]
@gyaresu don't think so

1) The first line is just JSON (OK, so that's organizers). If we can pull / include that in "our" home page at (2), that would be nice. But, doesn't need constant editing.

2) The second is "our" web page, that is publicly visible at http://nodeschool.io/vancouver. I would suggest that we do all communications there.

The flow for events is
- make a post with all info -- see https://github.com/nodeschool/vancouver/tree/gh-pages/_posts -- and embed tito link for signup
- go to tito and fill in basic info
- share link to nodeschool.io/vancouver as the canonical place to go
- non-profit!

3) We really shouldn't be sharing / showing the ti.to page directly -- what if we move off ti.to? The front page there should just say a brief about and say, go to http://nodeschool.io/vancouver for info

**Comment by gyaresu** [comment]
@bmann I wasn't very clear with the first link.

http://nodeschool.io/vancouver/ is only editable from the `gh-pages` branch of the first link.

I think you've mixed up the second link because that's our repo's readme.

**Comment by bmann** [comment]
Which is why I set the gh-pages as the default but y'all changed it back -- you can have something in the README, but it can be focused on what do it in the repo, and otherwise have a big ass link that says "visit this at https://nodeschool.io/vancouver"

I tend to set repo README as "how do I deal with this repo". We might also keep master branch as some HOW TO stuff, but really, it's all stuff that should be easily web visible, so I would also advocate for _posts or pages for that.

This is me saying I'm web centric rather than repo-centric, esp. if we're trying to appeal to beginners. We just should be somewhat clear on how / what we want to do for updates and edits. Looking at this repo and the website, I can't tell there are new events RIGHT NOW.

**Comment by gyaresu** [comment]
Sorry for the delay. Distractions all around me.

I completely agree with you. 

**Proposal:**
- We use the _One True Website™_ at http://nodeschool.io/vancouver with a link to the booking tickets page on ti.to.
  (_There's an option under ti.to for a redirect [back to our homepage] after booking a ticket but not any code to embed._)
- This repos `readme.md` gets a **MASSIVE** link to the website and maybe a link to issues.

That keeps Ti.to restricted to the specifics of ordering tickets and nothing else such as the mailing list.

I'm happy to do all this tomorrow or together with you @bmann if you're around and are ok with the proposal(?)

I think this is a good and reasonable tidy up unless there's problems with eventually moving nodeschool/vancouver  to vancouver/nodeschool?

Pinging @sintaxi & @lvivier for transparency purposes.

**Comment by bmann** [comment]
Yes. 

Not sure what you mean by Vancouver/nodeschool?

Regardless, cool web permalinks don't change so it shouldn't matter.

**Comment by gyaresu** [comment]
https://github.com/nodeschool/vancouver/issues/15

**Comment by gyaresu** [comment]
**Would anyone like to re-create the homepage?**

Ok. I just want to nuke the austin template we're using on the website.

The horrible blend of markdown, html & templating.

Which probably means I shouldn't be the one to do it.

I'm very utilitarian in my design approach. AKA: [Gareth has no style](https://gareth.codes)

Volunteers?

**Comment by bmann** [comment]
@gyaresu that's how Jekyll gets built on Github Pages. I nominate @kennethormandy, since he also owes us a logo :)

If you can edit the CONTENT -- links and wording and such -- that will help with design.

**Comment by gyaresu** [comment]
I do love jekyll. It's what I use just without mixing in html.

I think I'm just grumpy at gnuradio today :)

**Comment by keywordnew** [comment]
Closing as signup is now handled by meetup.com page
