### ISSUE TITLE
Using the GPIO pins on the Raspberry Pi with Node

### ISSUE THREAD

**Issue by gyaresu** [nodeschool/vancouver#13]
This is just a starting post for hopefully an interesting thread on using the Raspberry Pi as both Node.js host and In-Out pins for controlling sensors, motors, devices etc.

http://johnny-five.io/examples/raspi-io/

My old Pi. (Others are listed)
http://johnny-five.io/platform-support/#raspberry-pi-model-b-rev-1

The Raspbian Operating System (It's basically Debian):
http://www.raspbian.org/RaspbianStartHere

IO library that lets you run Johnny-Five on the Raspberry Pi:
https://github.com/nebrius/raspi-io

The Raspberry Pi pins have funny names:
https://github.com/nebrius/raspi-io#pin-naming

**Comment by lvivier** [comment]
@gyaresu where did you buy your pi? I remember we came across [buyapi.ca](http://www.buyapi.ca/), they seem pretty legit…

**Comment by gyaresu** [comment]
Mine are old now:
That site looks good. There's a list of places on the [Vancouver Robotics - Link to Vendors](http://vancouverroboticsclub.org/2011/07/17/links-to-companies-vendors-etc/) page.

**Comment by Qard** [comment]
Just a few notes:
- NOOBS Raspbian is super old. You want the actual Raspbian-only download on the pi website.
- You may or may not have to do a dist upgrade from Raspbian wheezy to jessie.
- [nvm](https://github.com/creationix/nvm#install-script) is an easy way to get node/io.js installed.
- johnny-five does not currently build on io.js 3.x.
