### ISSUE TITLE
August 29th 2015 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#14]
Discussion for the next NodeSchool!

**Comment by gyaresu** [comment]
PING!

**Comment by gyaresu** [comment]
#### I see three categories of potential interest:
- **Beginners** - `learnyounode`(?)
  - The big screen meeting room
- **Intermediate** - `nodebot-workshop`
  - More arduino + `johnny-five` magic?
- **Intermediate/Advanced**
  - Adopt a workshop and look at how they run
  - Create extra exercises and submit them as Pull Requests
  - Fix some bugs 

**Thoughts?**

**Comment by Qard** [comment]
I'll probably remember to bring my hardware stuff this time. Other than that, 

Also, stream-adventure, webgl-workshop and shader-school are fun ones to do.

**Comment by gyaresu** [comment]
I think it's good if at least one or two folks take the lead on a particular workshop when doing it as a group.

webgl-workshop gets pretty intense quickly but it is pretty
stream-adventure is a really good option
I haven't done shader-school, it's showing some deprecated packages and failing for me while installing.

What do you think about [Building workshops](http://nodeschool.io/building-workshops.html) Stephen?

I'm quite keen on empowering folks to contribute back to workshops with either bug fixing or exercise creation.

I think all of this depends on how many mentors we get lined up before-hand.

**Comment by Qard** [comment]
Building new workshops or helping maintain existing ones is always an admirable goal. Might be good to have git-it and how-to-npm handy though, for the newbies. _Using_ modules is one thing, _writing and maintaining_ them is another. When you aren't yet confident you know what you are doing, following exact instructions is a lot more comfortable than operating on your own.

**Comment by gyaresu** [comment]
https://github.com/nodeschool/vancouver updated. 

Creating Tito event and emailing previous attendees.

**Comment by gyaresu** [comment]
I want to create a mailing list for folks to subscribe to.
My preference is for http://librelist.com

Tito is not very easy to email previous attendees and not everyone is on Twitter. (The buttons are there in some cases but is just a buggy)

Email FTW.

Thoughts?

**Comment by gyaresu** [comment]
vancouver.nodeschool@librelist.com created

**Comment by gyaresu** [comment]
Tickets for 29th August nodeschool event are live!
https://ti.to/nodeschool-vancouver/2015-08-29

Emails to follow.

**Comment by lrlna** [comment]
@gyaresu What were you thinking in this one? I didn't quite understand. 
 https://twitter.com/gyaresu/status/631594130045468672

Also, sorry I don't check here very often!! Y'all can ping me and things 🎉💅🙋🏼

**Comment by gyaresu** [comment]
Just reaching out to you folks about where else we might share the NodeSchool events. 

Like if there are email lists or get a retweet from Ladies Learning Code or just generally how we can get up to a gender/minority balanced group. 

## Dreaming big. 

Gareth

Crypto: https://keybase.io/gyaresu

[Sent via magical thumb-typing  pocket computing device]

**Comment by lrlna** [comment]
@gyaresu I think Ladies Learning Code normally keeps their newsletters to their own events. However, I've been thinking of talking about it to our chapter lead to see if we can get some collaboration going with local meetups. Or at least the mention of further resources/groups learners can get to.

BTW, thanks for organizing all these ^.^

**Comment by Qard** [comment]
:+1: for figuring out how to broaden diversity. Especially in the mentor group which is currently rather white and male...
