### ISSUE TITLE
move to vancouver/nodeschool?

### ISSUE THREAD

**Issue by sintaxi** [nodeschool/vancouver#15]
Curious what everyones thoughts are of moving from nodeschool/vancouver to vancouver/nodeschool? Due to the success of nodeschool I think its outgrown this format. Doing this and other meetups under a local org is a logical change IMHO.

**Comment by lvivier** [comment]
I don't see the advantage of moving it vs keeping it on /nodeschool but I'm fine either way. As long as ppl can find it and it doesn't disrupt too much.

**Comment by Qard** [comment]
I'd just make a repo that points here in vancouver/nodeschool, much like I did for vancouver/dancejs.

**Comment by sintaxi** [comment]
@lvivier the advantage is we would get notifications on other events happening in vancouver rather than other locations nodeschool is happening.
