### ISSUE TITLE
Future of NodeSchool - Vancouver & other meet-ups

### ISSUE THREAD

**Issue by gyaresu** [nodeschool/vancouver#18]
# Hi folks!

Firstly a big shout out to our hosts Retsly/Zillow thanks to @lvivier. Great venue and people.

I want to use this thread as a check to see if the current format is working for everyone, and whether there are any changes that might improve our afternoon of code?

That got me thinking about the relationship between local tech groups and the room for expanding the overlap between interests/disciplines.
### Firstly: "Wait... Why not just use Meetup.com?"

Meetup is a business and they charge money if you run a group. 
That's not to say it might not be worth it for groups but it doesn't sit well in terms of Open Source Software and who 'owns' a community.

```
Basic
Up to 50 members and 4 organizers
$14.99/month

Unlimited
Unlimited members and organizers
$19.99/month
```

In principle I'm not against paying for a service but not when you pay so the service can own you. (thoughts?)
### GitHub repo move

There's a ticket about moving this repo to vancouver/nodeschool instead of nodeschool/vancouver and I like the thinking around exposing other local meet-ups and groups. (Issue: https://github.com/nodeschool/vancouver/issues/15)

How would that look if it was an up-to-date and full list of all the hackerspaces/meetups and groups currently active in Vancouver? (I think it would be awesome)

Or does that already exist and we just need to tie into an existing network?
### Local scope

There seem obvious relationships such as @sintaxi's [Node Brigade](http://www.meetup.com/node-brigade-vancouver/) but perhaps there's also the opportunity to overlap and expand the ways in which we _Node_.

My interests for example currently fall into three categories broadly titled **Internet of Things**. 
- hardware gadgets: tessel, arduino, robots
- SDR (Software Defined Radio): gnuradio, HackRF
- Node: JavaScript all the things™

Libraries like 'johnny-five' via nodebots and folks like [Max Ogden getting into SDR](https://twitter.com/maxogden/status/632563414339076096) makes for some great convergence. 
### Final thoughts for now...

`Atwood's Law: any application that can be written in JavaScript, will eventually be written in JavaScript.` - [Jeff Atwood](https://blog.codinghorror.com/the-principle-of-least-power)

Javascript & Node gives us the great opportunity to work/play and collaborate with people across many industries and skillsets. More so than any other technology I can think of right now.

Mutual learning is a wonderful thing. What (if anything) are you going to do to expand the principles of sharing and openness in Vancouver? :)

**Ok all you lurkers, tell us what you think!**

**Comment by lvivier** [comment]
## Study Group

How about a study group in between regular NodeSchools? [Max Ogden is organizing one in Portland](https://github.com/nodeschool/pdx/issues/3).

**Comment by gyaresu** [comment]
I would like to revisit folks' thoughts on hosting the group on meetup.com

The number one reason I would be fine with doing that would be exposure and making it easy for folks to be reminded regularly.

The current methods are sufficient for completing the task buy i'm not sure they're doing the job in terms of outreach.

https://www.meetup.com/pricing/ — currently US$14.99/month (US$180/yr)

So that means we ask for donations or find sponsorship. Perhaps tied to a more permanent venue?

And maybe the meetup group could be _British Columbia Nodeschool_ so @lvivier could use it for a Vancouver Island group. And anywhere else in the province...

Thoughts?

Other relevant issue: https://github.com/nodeschool/vancouver/issues/42

**Comment by lvivier** [comment]
@gyaresu there's [nodeschool/victoria](https://github.com/nodeschool/victoria) actually, need to hassle @matchdav about letting the ol' Powers combine. 

I still think Meetup.com is pretty underhanded but really anything that improves outreach/engagement is probably good. Would you replace Ti.to with Meetup?

**Comment by thomasMinshull** [comment]
re issue #42 it looks like you can now close a meetup group https://www.meetup.com/help/article/465011/

**Comment by thomasMinshull** [comment]
Does that help to elevate the concerns about ownership of the group? 
I think it's an effective tool for getting the word out. If we could get sponsorship, or find another way to cover the cost

**Comment by lvivier** [comment]
Looks good to me. I may have one or two leads on sponsorship.

**Comment by gyaresu** [comment]
## Vote: Create meetup.com group

**A single vote per IP is allowed for a given poll so maybe vote and then +1, party, or smiley face this post? (so we can see who voted)**

### Click the  images below to cast your vote (once!)

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ8CDFZED990AC39RC67WN94/Create%20group%20on%20Meetup.com)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ8CDFZED990AC39RC67WN94/Create%20group%20on%20Meetup.com/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ8CDFZED990AC39RC67WN94/Keep%20our%20existing%20systems)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ8CDFZED990AC39RC67WN94/Keep%20our%20existing%20systems/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ8CDFZED990AC39RC67WN94/This%20poll%20is%20fundamentally%20flawed)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ8CDFZED990AC39RC67WN94/This%20poll%20is%20fundamentally%20flawed/vote)

**Comment by kennethormandy** [comment]
I’m not going to vote since I still haven’t attended, but hopefully my experience with [Type Brigade](https://meetup.com/typebrigade) (and previously helping with CSS Brigade and Node Brigade) is useful in some way:

- Meetup is _very_ helpful for discovery
- Meetup has are no options for by-donation, pay-what-you-want, or early-bird discounted ticketing, which can be limiting for events that want to be mostly free to attend
- Meetup is difficult to move away from as a platform (although [sounds like this is improving](https://github.com/nodeschool/vancouver/issues/18#issuecomment-319881224)) 
- In my opinion, Meetup is a _much_ better platform than GitHub for reaching out to the people who would be the most likely to benefit from Node School, but that’s also be true of other platforms.

I would definitely support moving off of GitHub (or at least moving the official event off of GitHub, event if the organisation discussions stayed here). Some organisations also post all their events on Meetup but just as a link to some other ticketing system.

**Comment by keywordnew** [comment]
NodeSchoolYVR now has a [meetup.com presence](https://www.meetup.com/nodeschool-vancouver/). There are concrete plans to do regular meetups, albeit on the smaller side until we can find larger venues willing to host, and the schedule can be found in SCHEDULE.md at root.

Closing this issue for now as I feel the original subject has been addressed; but feel free to reopen or make a new one for future discussion.

A study group as suggested [earlier](https://github.com/nodeschool/vancouver/issues/18#issuecomment-158685800) would be great to have. I'd love for discussion on that to continue and would encourage an issue about that to be opened! 💛
