### ISSUE TITLE
**cancelled** September 26, 2015 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#19]
**Update** - No NodeSchool for September. See you in October!

**Comment by gyaresu** [comment]
##### Job list:
- Theme for the event
- Website consolidation (maybe @gyaresu)
- Ti.to event (@gyaresu)
- Presentation / combination with NodeBrigade?

What am I forgetting?

**Comment by Qard** [comment]
I'll be missing this one. I have a wedding to go to.

**Comment by gyaresu** [comment]
@Qard Well that sucks and we'll miss you.

**Comment by Qard** [comment]
I look forward to seeing you all in October. :wave:

**Comment by lvivier** [comment]
cc @gyaresu 

I'm not going to be available for this month's event either, we're selling our place this month and it's been really busy. Maybe we can do one early October instead?

**Comment by gyaresu** [comment]
1. Good luck
2. Let's reconvene next month
3. I'm writing a lot of C code :)
