### ISSUE TITLE
Create a logo for the Hexdex

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#2]
The [Hexdex](http://nodeschool.io/hexdex.html) is an index of hexagon logos for all the NodeSchool chapters. Does someone want to make one for YVR?

**Comment by kennethormandy** [comment]
I could probably take that on.

**Comment by gyaresu** [comment]
No pressure @kennethormandy 

It only has to be the **BEST LOGO IN THE WORLD** and sum up the total and utter essence of everything that is Vancouver

no pressure...

but srsly... Thank you.

 ![Thanks!](http://danbaldini.com/wp-content/uploads/2014/06/unicorn_pooping_a_rainbow_20px.jpg)

**Comment by kennethormandy** [comment]
Rough sketch that I think is getting closer to what I’ll try:

![2015-05-22 11 47 02](https://cloud.githubusercontent.com/assets/1581276/7777581/25e2826a-0079-11e5-8d42-b657aaa1c276.jpg)

The NodeSchool chapter logos are very line-based, and Vancouver has this amazing history of being a neon capital. That’s not really the case anymore, but Granville St. is has the legacy of that. Going over the bridge towards Granville St. in the summer also gives you that view of Vancouver that it is well known for: you get the greenery, the water, the glass buildings, and the mountains all at once.

So I’m going to try and put that “Welcome to Vancouver” moment into the badge, but play up the neon signs on the buildings to combine some Vancouver history and compliment the existing NodeSchool illustrations.

**Comment by gyaresu** [comment]
@kennethormandy You don't mess around!

**Comment by sintaxi** [comment]
better get it right @kennethormandy! :)

**Comment by lvivier** [comment]
:candy: sweet, looking good!

**Comment by bmann** [comment]
w00t

**Comment by lvivier** [comment]
@kennethormandy did you make any progress on the logo?

**Comment by kennethormandy** [comment]
## Design Critique

Better late than never, right?

![nodeschool-4](https://cloud.githubusercontent.com/assets/1581276/10658132/beae7af2-7848-11e5-8ca6-ebbbee777b0e.png)

So this is largely based on the sketch I posted here before. The mark is supposed to follow the visual language that the existing Node School logo sets up: drawn distinctively but entirely with lines, this is a respectable place people are welcome to go to, and the eye is drawn towards the door in the middle:

![](http://nodeschool.io/images/schoolhouse.svg)

Our variation draws from the Granville St. bridge to show the road to Node School. The outer parts of the mark reference some of the glass everywhere look of Vancouver, and the left side of the mark has a couple of signs, very loosely referencing the neon history of Granville St.

The middle building is round, to try and reference the Central Library, with the outer skyrises sort of doubling as the outer parts of the building (this colour is just to highlight it):

![nodeschool-5](https://cloud.githubusercontent.com/assets/1581276/10658215/916344b4-7849-11e5-8b9a-916c0eab991b.png)

Of course, this isn’t geographically accurate, but in either case we get the mountain behind as you’d expect. The library is a unique landmark in the city and makes sense to relate to the educational aspect of Node School, so I thought that was appropriate to include.

On the left and right of the bridge, we get more of a reference to the water, beaches, and parks of Vancouver. By keeping it all geometric and relatively simple, the visual style should still fit in or alongside the existing Node School identity and work at a smaller size (although I will make sure to test this, if you want to do stickers or anything).

The colours aren’t finalised, and any feedback on that would be great. Also wondering if we should go with VAN or YVR at the bottom, if you have an opinion on that. Here are some additional colour tests:

![nodeschool-2](https://cloud.githubusercontent.com/assets/1581276/10658310/6ed34bd2-784a-11e5-822e-aa8fe5f7cc3c.png)

This one is a little too ’80s I think:

![nodeschool-3](https://cloud.githubusercontent.com/assets/1581276/10658309/6ed22d2e-784a-11e5-970a-e13a6bba5af2.png)
![nodeschool-6](https://cloud.githubusercontent.com/assets/1581276/10658355/dd95ae5c-784a-11e5-9a0f-9601f7363387.png)

Most of the chapters seem to go for fairly bright colours, and I wanted to avoid picking something that would interfere with the existing Node green, or the bright Node School yellow, while still looking fine alongside them.

**Comment by sintaxi** [comment]
Bravo! :clap: 

No such thing as "too 80's" though. :)

**Comment by sintaxi** [comment]
I like the subtle contrast ![subtle contrast](https://cloud.githubusercontent.com/assets/1581276/10658310/6ed34bd2-784a-11e5-822e-aa8fe5f7cc3c.png)

**Comment by JimFung** [comment]
I also like the all blue one. What is everyone's opinion on adding another colour to the mountains? I think it'd help make it standout a bit more.

**Comment by lvivier** [comment]
@kennethormandy awesome, thanks for doing this!

I'll echo @JimFung's comments. Really I like them all. What's next? Add it to the [hexdex](http://nodeschool.io/hexdex.html) I guess?

**Comment by kennethormandy** [comment]
Thanks! I will wait a bit for feedback, post another colour iteration here, and depending on how that goes, get you an “Official” package with vectors for print and web, different sized pngs, etc. Please don’t use the drafts for anything :) There’s still some minor things to fix (not all the corners on the hex border are rounded, etc.) I can open a PR on the Hexdex then too.

And do let me know what you prefer, YVR vs. VAN!

**Comment by JimFung** [comment]
I prefer YVR, its sort of like a secret code for us vancouverites :) I doubt many people outside of vancouver will know what it means, unless they travel to vancouver a lot. 
Thanks for the work on the logo btw! looks great!

**Comment by lvivier** [comment]
+1 to YVR

**Comment by gyaresu** [comment]
Love 'em.

I'm going to try giving feedback without linking to the images... here goes.

I think the two versions that use the darker colour for the building creates better depth of field and really 'pops' the buildings. (plants in the foreground and mountain in the back are lighter colour)

But at the same time I love the "80's one" also because you've used the two separate colours for the water vs. the land (under the trees).

So my vote is some combination of split mountain, split water/ground and dark building.

I was going for **worst client EVAR**. How'd I do?

**Comment by gyaresu** [comment]
Which, now I read my own spiel, is actually the "little too 80's" one.

yeah... I vote that. 

+1 YVR

**Comment by lrlna** [comment]
These are _gorgeous_ @kennethormandy !! 
+1 on blue one +1 YVR

**Comment by kennethormandy** [comment]
Alright! I can do another take on the blue one and fix up the remaining issues. Thanks for the feedback and kind words everyone. It also seems like YVR is good with everyone, so I will keep it as that unless anyone has any major objections.

I saw something about getting these printed for the event on the 21st, which might be a little unrealistic depending on when I can get the final version up here, but I will see what I can do. We have been happy with Sticker Mule, and their turn-around time is only five days, but it costs a lot more for rush shipping. I will aim to have the logo _done_ for the next event, and then we can order stickers after that.

**Comment by lvivier** [comment]
@kennethormandy thanks for all your efforts! This is great. Look forward to seeing the final. No pressure re: stickers, I added it to the event issue just so I wouldn't forget to do it in case we had it ready.

**Comment by JimFung** [comment]
+1 to stickers, my mac is looking pretty boring right now

**Comment by Qard** [comment]
I'm going to need to buy a new laptop to have space for more stickers! :open_mouth: 

They look great though!

**Comment by xer0x** [comment]
How we get stickers now?

**Comment by lvivier** [comment]
Just a reminder for myself that there's a drive to create a NodeSchool sticker pack with stickermule: nodeschool/organizers#292. It would be awesome to get the YVR sticker into the hexdex in time.

**Comment by kennethormandy** [comment]
@lvivier I will try and do the final fixes later this week. Let me know if they post a deadline for that collection and you don’t have the final files from me yet.

**Comment by forivall** [comment]
Oh, cool, there is one being created! That's way better than the one I made while talking about nodeschool on meatspace.
![1446794611957](https://cloud.githubusercontent.com/assets/760204/11409058/47553bb8-9372-11e5-8a16-fa295ae1f3aa.gif)

On a more serious note, :+1: on the subtle green/teal/blue color scheme.

**Comment by gyaresu** [comment]
Yeah but Kenneth's isn't animated. So there's that.

**Comment by lvivier** [comment]
@kennethormandy did you ever get the final tweaks in? The stickermule pack idea is still in process, but @JimFung is dying to get some NodeSchool YVR stickers to spruce up his grey dull macbook.

**Comment by JimFung** [comment]
its true, my macbook is looking pretty pathetic.

**Comment by kennethormandy** [comment]
![nodeschool-v2-purple](https://cloud.githubusercontent.com/assets/1581276/12832578/9f99c612-cb4f-11e5-8877-62f535056484.png)

Here are the updates I’ve been meaning to make. Here’s [the concept from before](https://github.com/nodeschool/vancouver/issues/2#issuecomment-150121653), which is still the same:

> Our variation draws from the Granville St. bridge to show the road to Node School. The outer parts of the mark reference some of the glass everywhere look of Vancouver, and the left side of the mark has a couple of signs, very loosely referencing the neon history of Granville St.
> 
> The middle building is round, to try and reference the Central Library, with the outer skyrises sort of doubling as the outer parts of the building … On the left and right of the bridge, we get more of a reference to the water, beaches, and parks of Vancouver. By keeping it all geometric and relatively simple, the visual style should still fit in or alongside the existing Node School identity and work at a smaller size.

Most of the changes since last time are corrections to the drawing:
- Thick, black border is back, to match the other Node School hexes. The rounded corners on the hex are fixed.
- Some spacing and alignment issues fixed up in various places, like the square and rectangular windows, the underline under “Node School,” and where the signs on the building are placed.
- A third colour has been introduced. I think purple still works best to sit alongside the Node and Node School logos, and the darker purple background allows the foreground elements to come through without adding a lot of complexity. The drawing can still work as a line drawing if it needs to.
- I removed the windows and re-drew the top of the central library / Node School building. I think they were adding more than they were taking away.

Before and after:

![nodeschool-v2-diff](https://cloud.githubusercontent.com/assets/1581276/12857441/1a38efec-cbff-11e5-87a5-c0d304ba9824.png)

Let me know if you have any feedback, specifically about the changes that have been made since the last iteration. I’m ready to commit the SVGs so that we can actually start doing stuff with this!

**Comment by lrlna** [comment]
Omg Kenneth, it looks so good!!! Ahh!! 🙏🌟❇✨

**Comment by forivall** [comment]
I love the updated colour scheme with the stronger purple. My only critique is that the top of the building now looks a little bit too tall, like someone with a big forehead :3. But oddly enough, I mainly notice it in the small size.

**Comment by gyaresu** [comment]
I love it Kenneth. Really.

Well done mate. Thanks so much for putting all the work in.

**Comment by lvivier** [comment]
@kennethormandy woo hoo! Looking good. Whenever you are comfortable w/final SVGs I will order us all up some stickermule hexes!

**Comment by JimFung** [comment]
Eagerly awaiting nodeschool stickers. Thanks for designing the logo @kennethormandy!! It looks really good!

**Comment by kennethormandy** [comment]
Apparently I forgot to wrap this up ages ago, sorry. Since it’s already on the site and Twitter now, feel free to use this version to print stickers too, if you still want. Let me know if you need any changes to the files for that.

**Comment by gyaresu** [comment]
Excellent. Thanks @kennethormandy!

![bitmoji](https://render.bitstrips.com/v2/cpanel/7897753-322108779_2-s4-v1.png?transparent=1&palette=1&width=246)

## Next jobs

 - [ ] Update the website to credit Kenneth and link to this design thread
 - [ ] $printing stickers
 - [ ] Add our sticker to the [nodeschool hexdex](https://nodeschool.io/hexdex.html)
 - [ ] Decide if we're [going to use](https://github.com/nodeschool/vancouver/issues/18) meetup.com

Happy to make a new issue for this task list if that keeps it cleaner from a management point.

**Comment by nated0g** [comment]
![nodeschool-yvr-sticker](https://user-images.githubusercontent.com/6021620/32409180-1db53ae8-c164-11e7-9260-f7fe2c9723bc.jpg)

Look what showed up from Stickermule on a snowy Saturday...

Great job on the logo @kennethormandy.

**Comment by evscott** [comment]
Those are awesome! Where/when can I get one?

**Comment by nated0g** [comment]
I'll bring them to the next monthly meetup, whenever that happens.

@gyaresu had also suggested another meetup, sooner, for working on some of the workshoppers.  I'll make another issue for that.

**Comment by keywordnew** [comment]
The excellent Hex logo created by @kennethormandy is being used across NodeSchool YVR materials and has been for a while. [This PR](https://github.com/nodeschool/nodeschool.github.io/pull/617) adds it to the Hexdex. When it lands, I'll close this issue. Please review! 😄

**Comment by keywordnew** [comment]
<img width="810" alt="screen shot 2018-05-11 at 15 40 05" src="https://user-images.githubusercontent.com/10335475/39949746-aa66d076-5531-11e8-8d5e-49df8f59236e.png">

Now all we need are stickers 😉

Closing for now.

**Comment by halkeye** [comment]
@chowdhurian it doesn't line uppppppp

**Comment by keywordnew** [comment]
@halkeye Lol, not entirely sure why

**Comment by nated0g** [comment]
I actually had stickers made a few months ago, haven't had time to attend
any of the meetings since the first one I went to.  I'll make it out one
day soon and bring the stickers!
