### ISSUE TITLE
Debugging in nodejs

### ISSUE THREAD

**Issue by JimFung** [nodeschool/vancouver#20]
I'm usually just using console.log to print out values but this is quite tedious and sometimes doesn't give you the full scope of what is happening in your code. Does anyone have tips/tricks for debugging in node? or know of a good tutorial for debuggers? I've seen the debugger that strongloop maintains but that also seems kind of buggy at times. Thanks!

EDIT: I'd label this as a question but i don't have privileges :p

**Comment by lvivier** [comment]
Node comes with a [built-in debugger](https://nodejs.org/api/debugger.html):

```
$ node debug index.js
```

Apart from that, [node-inspector](https://www.npmjs.com/package/node-inspector) is the best tool available, afaik. I think that's the one StrongLoop maintains. For the uninitiated, it starts a little web server at `http://localhost:5858/` and you debug with the Chrome DevTools. It looks like this:

<img width="1037" alt="node-inspector" src="https://cloud.githubusercontent.com/assets/679312/10278737/9f25cec4-6b14-11e5-9cb9-5fe730bbd532.png">

Install it with npm and you can run it in place of node during development:

```
$ npm install -g node-inspector
$ node-debug index.js
```

If you use mocha for unit tests it works the same:

```
$ node-debug _mocha
```

**Comment by JimFung** [comment]
I guess I'll give node-inspector another shot then. Thanks!

**Comment by Qard** [comment]
Yep, node-inspector is currently the best option. There's some people at Google working on pulling the dev tools components out of blink so we can have a more complete dev tools experience with node, but that isn't ready yet.

You can also use mdb_v8 for lower level debugging and dtrace, lttng or etw for tracing.
