### ISSUE TITLE
October event?

### ISSUE THREAD

**Issue by Qard** [nodeschool/vancouver#21]
Is there going to be an October event? If so, I'd recommend we do it on the 24th, as the next Saturday is Halloween.

**Comment by JimFung** [comment]
+1

**Comment by Qard** [comment]
We could also do it a week later, on November 7th, if the 24th is too soon.

**Comment by lvivier** [comment]
Sure, let's do it—I'll confirm we can use the space tomorrow and I'll update this issue then.

**Comment by Qard** [comment]
I'm going to selfishly vote for November 7th, as my father will be in town and he's been wanting to learn some node. :smiley_cat:

**Comment by lrlna** [comment]
I teach with Ladies Learning Code both days. Suckssss :|

**Comment by Qard** [comment]
Maybe we could try a Sunday this time around?

**Comment by lrlna** [comment]
That's not a bad idea!

**Comment by jfmaggie** [comment]
Sunday sounds much better :)

**Comment by lvivier** [comment]
The Zillow team including me will be in SF November 6-8 unfortunately, so the Z office won't be available then. What do you think?
1. Rustle up another space for November 8
2. Usual spot October 25

**Comment by Qard** [comment]
25th is probably easiest.

**Comment by lvivier** [comment]
Event thread! #22
