### ISSUE TITLE
add a blurb on mentoring at nodeschool-Vancouver edition

### ISSUE THREAD

**Issue by lrlna** [nodeschool/vancouver#26]
I thought it to be a good idea to let both learners and mentors about some of the mentor responsibilities/best-practices/guidelines, especially as our chapter is growing (yay!). We are bound to get more and more learners/mentors joining, and some folks might have unanswered questions. I, for example, totally did not know what I was suppose to do as a mentor on the first node school we hosted ¯_(ツ)_/¯. 
Nodeschool has a brilliant write up on [Event Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) that I am thinking of including in our own guidelines. If folks are okay with this, I'll submit a PR to add this to our readme.

**Comment by Qard** [comment]
:+1: 

I would try to be clear that there is not necessarily a binary state of student or mentor though, to encourage past students to help mentor on the things they've already learned about.

**Comment by lrlna** [comment]
:cool:, definitely agree @Qard

**Comment by lvivier** [comment]
:clap: great idea!

**Comment by lvivier** [comment]
@lrlna still taking this one on?

**Comment by lrlna** [comment]
yes! I keep forgetting to do this ugh ugh ugh.
