### ISSUE TITLE
Pro/Con's of mirroring event on Meetup.com

### ISSUE THREAD

**Issue by gyaresu** [nodeschool/vancouver#42]
Just wanted to start a thread discussing if there are advantage to mirroring events on the Meetup website.

I notice there's a new [Port Coquitlam Node and NodeBots Meetup](http://www.meetup.com/Port-Coquitlam-Node-and-NodeBots-Meetup/events/231614970/).

Thoughts?

**Comment by yoshuawuyts** [comment]
@gyaresu Meetup is def how I find out about new events when traveling to new cities - think a lot of people do. Would def be a plus for me (':

**Comment by Qard** [comment]
Meetup is kind of expensive though.

Also, you can't ever _stop_ using Meetup. There's no way to shut down a group, you can only step down as organizer and hope no one else claims control of the group to spam all the users or something terrible like that. 😞
