### ISSUE TITLE
Mentor hack/study session

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#46]
At the most recent event we talked about maybe doing a mentor hack session. The idea would be to work on workshoppers, the web site, and things of that nature. Anyone interested in something like that?

**Comment by JimFung** [comment]
I'm probably too busy this month to do this, given my profs have decided to murder me slowly with midterms. I still think it's a good idea though!

**Comment by Qard** [comment]
I'd be happy to participate, though I'm out of town until Monday so it'd have to be after that if I'm to attend.

**Comment by lvivier** [comment]
OK cool, no rush or anything…does early November work? @Qard maybe we could even expand it a bit to include YVR JS community things in general?

**Comment by Qard** [comment]
Should work. As for scoping, not sure. Keeping it limited to nodeschool stuff would be good for focus, but it might also limit the selection of people that attend.

**Comment by lvivier** [comment]
I'd still like to do this. How are the first two weeks of January for everyone?

**Comment by Qard** [comment]
I'm free basically any day except this Saturday.

**Comment by lvivier** [comment]
Closing due to old.
