### ISSUE TITLE
April Nodeschool

### ISSUE THREAD

**Issue by donburks** [nodeschool/vancouver#51]
Greetings one and all! How are we feeling about getting an April session going at the end of the month? We'll(Lighthouse) be happy to be venue host again, as well as offer some promotion help and even do a Picatic page if it helps get signups going.

**Comment by Qard** [comment]
Yeah, certainly. I didn't have the time to deal with it for the end of March, but it'd be good to get an April event moving soon.

**Comment by Qard** [comment]
@donburks Can you lead this one? It looks like I might be away this time. At the least I'm too busy to arrange it right now. I can tweet or get stuff in ti.to if you need though. Picatic is fine too, if you prefer to use that.

**Comment by donburks** [comment]
Yeah, I am happy to do that. Let me doublecheck with Sarah F about availability and I'll update the thread later today.

**Comment by halkeye** [comment]
Ooooh, its not dead! april looks pretty tight at this point (over half way through the month), but I can help out april or may pretty easily.

**Comment by Qard** [comment]
Yeah, I'm out of the country until the 27th, so it's up to Don to pull something together this time, if he has the time for it.

**Comment by heatherbooker** [comment]
Hi! Is there a chance of seeing an event for May? I know myself and @halkeye would both be happy to help out! @donburks are you in charge of coordinating space with Lighthouse? :)

**Comment by Qard** [comment]
I'll be back in Vancouver in a couple days, so I'll definitely get started once I return on making a May event happen. :smile_cat:

**Comment by heatherbooker** [comment]
@Qard yay!

**Comment by darcyclarke** [comment]
Can this issue be closed? It seems specific to an old event
