### ISSUE TITLE
Impromptu July event/meetup?

### ISSUE THREAD

**Issue by darcyclarke** [nodeschool/vancouver#53]
Hey folks, 

I'm one of the NodeSchoolTO co-ordinator/mentors and was wondering if you might want to do an event this Saturday. I know it's a bit last minute but I'll be in town and wanted to see if we could get together. I'd be willing to do a talk or lead a workshop if that would help get folks out. I'm also cool with just getting a small group of folks together to talk shop or exchange notes on organizing these events.

Let me know your thoughts. I'm flying into Vancouver tomorrow morning so I'll be in the area either way. 

Cheers!
~Darcy

P.s. I know you've already scheduled an event in early August but I thought this could be something special since there might be a few folks in from Toronto (there's a TELUS off-site this week, which might also be a potential venue if we'd need one)

**Comment by lvivier** [comment]
I won't be in Vancouver then but @Qard ?

**Comment by Qard** [comment]
I'd be happy to do something, if there's a venue available. The 29th is nodebots day, which I hoped to align with for the latest event, but it's been hard arranging a stable venue lately so the date got pushed back a week.

@chowdhurian What do you think? Would you be down for an extra NodeSchool session this weekend?

**Comment by Qard** [comment]
BTW, I'm easiest to reach on Twitter: http://twitter.com/stephenbelanger

My DMs are open to all. 👌

**Comment by keywordnew** [comment]
@qard I'm in your DMs :)

**Comment by thomasMinshull** [comment]
I'm up for that

**Comment by darcyclarke** [comment]
It's only a couple days off so maybe a bit too ambitious to try and find a venue and run a full event; That said, could we pick a good coffee shop or some place downtown to meet up and hack together? I'm easy but just not familiar with the city and potential places to meet up

**Comment by Qard** [comment]
Yeah, it's probably a bit late for a full event, but I'd definitely be down for calling out for an impromptu coffee shop hack session, or mentor/organizer gathering. 💪

**Comment by keywordnew** [comment]
Lost + Found cafe has a good space for hack sessions :)

Have fun y'all. I wish I was there 💛

**Comment by darcyclarke** [comment]
I'm going to head to Lost + Found around 1pm today if anyone wants to join me.

**Comment by Qard** [comment]
Sure, I'll join. 👍

**Comment by darcyclarke** [comment]
@Qard looks like it's closed today (not sure why). I ended up heading around the corner to a place called "The coffee bar". It's pretty easy to spot me, I've got more stickers on my laptop then the average dev :P

**Comment by darcyclarke** [comment]
Thanks for meeting up @Qard @gyaresu @thomasMinshull! Was great to meet you all. We'll try and work together closely in the future. More hangouts I'm sure
