### ISSUE TITLE
August 10th 2017 nodeschool

### ISSUE THREAD

**Issue by gyaresu** [nodeschool/vancouver#54]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10211715-322108779_2-s4-v1.png?transparent=1&palette=1&width=246)

Please feel free to edit/add to this checklist and make sure to put your handle (name) on what you change/ are taking responsibility for. 

- Venue
  - [x] Confirm venue
  - [ ] Food provided?
  - [ ] Drinks provided?
- [x] Make the [10th August event](https://ti.to/nodeschool-vancouver/nodeschool-yvr-10th-aug-2017) live for "tickets" on ti.to
- [ ] Share regularly on Twitter
- [x] Make a Facebook event(?)
- Reach out to relevant orgs
  - [ ] Ladies Learning Code

**Comment by gyaresu** [comment]
@Qard Are we cool to tell folks on twitter that the event is being hosted at Lighthouse Labs?
Contact there we can "thank" via twitter?

**Comment by Qard** [comment]
Yep. 👍 

I've already tweeted a couple times mentioning lighthouse. 😸

**Comment by gyaresu** [comment]
Cool. So I've never been there. I'm thinking this is where we try finding Tom on Twitter/Github and rope him into the cunning plans. Get some venue details/instructions to share with folks who might want to attend.

**Comment by thomasMinshull** [comment]
https://twitter.com/thomasminshull

**Comment by thomasMinshull** [comment]
You guy's already have the LHL venue all set up?

**Comment by thomasMinshull** [comment]
I can contact Ladies Learning to code

**Comment by thomasMinshull** [comment]
Also do we have a meetUp group? Should I create one?

**Comment by gyaresu** [comment]
Hi @thomasMinshull /me waves
I re-opened this issue from a couple years ago where we decided not to use meetup because of the way it owns your group after that... https://github.com/nodeschool/vancouver/issues/18

I think the discussion is worth a revisit.

Also, apropos venue: It would be great to get some details on space etc. 

Also @darcyclarke might be able to follow-up on our conversation about  _That Telco Wat Does Node_

**Comment by thomasMinshull** [comment]
Here's a link to the FaceBook Event I created. https://www.facebook.com/events/298761563923591/?active_tab=about
I'm assuming the time is 6-9 but I didn't see that written down anywhere can someone confirm, thanks

**Comment by thomasMinshull** [comment]
also I don't seem to be able to edit the list above to tick off that task

**Comment by Qard** [comment]
Yep, 6-9. Didn't realize it wasn't on the ti.to page.I'll make sure that gets added.

**Comment by gyaresu** [comment]
Oh, I didn't think to look at the time. We used to do Saturday afternoons. Cool.

@thomasMinshull Can you see if you can request to join the team here: https://github.com/orgs/nodeschool/teams/vancouver/members

None of us got around to becoming Nodeschool owners so we can't directly add you.

**Comment by thomasMinshull** [comment]
Sarah at LHL is going to put a note in the next weeks LHL news letter as well.

**Comment by lvivier** [comment]
Break a leg everybody! Hope I can make it up to the next one 🎉

**Comment by gyaresu** [comment]
Next months planning: https://github.com/nodeschool/vancouver/issues/54
