### ISSUE TITLE
September event? 

### ISSUE THREAD

**Issue by ghost** [nodeschool/vancouver#55]
Hey! 

Joanna here from Telus Digital, @darcyclarke told me to get in touch about our event spaces. 

We have one training room in Telus Garden on Sat Sept 9 available for 24 people. I can check if its available other dates too, but is that enough room for you guys? 

Other things need working out too (volunteers for set up, security etc) but I'm sure we can manage that if the space is ok. 

Looking forward to working with you guys!

**Comment by gyaresu** [comment]
Hi @joannalcarson!

Well that is kind and delightful. We had a nice session tonight at Lighthouse Labs. About 15 people in all.

Even with a group as small as that the format is often best when there's some type of conference room for the larger (usually) getting started crew and some smaller breakout area(s) for folks doing other collaborative workshops. Tonight we had a small crew working with @Qard's Arduino kits and going through the [nodebot workshopper](https://github.com/tableflip/nodebot-workshop).

So mostly I think it's about the size of the room and acoustics if there's a group discussion around solutions.

Sorry about my time to reply (I've been travelling so had notifications off for this repo).

Looking forward to meeting you and arranging a pleasant afternoon's coding.

Cheers

Gareth

**Comment by ghost** [comment]
Hey Gareth! 

Thanks for getting back to me, I hope you had a great time travelling. 

From your message it sounds like our training room doesn't fit your requirements. Do you still want to keep this room for September?

**Comment by Qard** [comment]
I'd be happy to try it out for one event and see how it goes. It doesn't sound like it leaves a lot of room for growth though. More space might be required relatively soon as the event scales up.

I'm happy to come by and have a look at the space personally too and/or meet and discuss anything that might need discussing, if you want.

**Comment by ghost** [comment]
Great thank you so much! I'm based in Toronto, but let me connect you with my colleague in Vancouver. My email is joanna.carson@telus.com if you want to reach me there?

**Comment by ghost** [comment]
Is there another Saturday in September we can do it? Our volunteer is unavailable on the 9th.

**Comment by Qard** [comment]
Yep, I'm happy with whatever we can get.

**Comment by ghost** [comment]
Great I've put in a request for the week after!

**Comment by gyaresu** [comment]
Hello lovely folks.
Just bumping the thread and checking with @joannalcarson  if we can confirm venue.

 - [x] 16th September Telus venue

(will you be in town @darcyclarke?)

Also checking with @lvivier and @Qard for consensus to: 
 - [ ] Setup Meetup page
 - [ ] Confirm mentors (@thomasMinshull?)
 - [ ] Organise non-pizza based snacks for half-time
 - [ ] Create better list for notifications to similar groups (lighthouse labs, ladies learning code, etc.)
 - [ ] Other stuff...

![bitmoji](https://render.bitstrips.com/v2/cpanel/10219586-322108779_2-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by Qard** [comment]
Saturday 16th is the date we're working on, not Tuesday 19th. Just waiting in security confirmation and we can start promoting.

**Comment by darcyclarke** [comment]
@gyaresu @Qard as a heads up, I will be trying to fly out to support this (no promises) alongside @ruxandrafed; who I believe is going to be available to support/mentor more going forward (as she's actually based in Vancouver and is an all around awesome dev). Not sure if you have any kind of mentor vetting but hopefully you're okay with us joining your ranks as we're sort-of required to attend if we're going to host @ TELUS Garden. Hopefully we can lock in the 16th as the date and work on promoting it to the community.

**Comment by Qard** [comment]
No mentor vetting at our current scale. Regardless, we're happy to have you all! 😎

**Comment by gyaresu** [comment]
Thanks Darcy! Hi @ruxandrafed!

There's no mentor vetting as it's usually a lovely and different group each time depending on what's going on in folks' lives.

And it's the enthusiasm of _anyone_ who wants to take on that role which makes the event still happen.

Super stoked to meet new folks and nerd out. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/10221939-322108779_2-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by thomasMinshull** [comment]
I'm not going to be in town for the 16th :( 
I can still help organize :)

**Comment by thomasMinshull** [comment]
I'll Talk to Sara at LHL and get her to put an announcement in the Alumni News letter. I can also ask her to reach out to Ladies Lean to code. As far as the list goes I can also reach out to the other Node meetups on Meet up. Re confirming Mentors, how would I get ahold of them (just Gitter?) also is there a list of (previous) Mentors??

**Comment by JimFung** [comment]
@thomasMinshull There is a list of mentors on the README for this repo, though the list might be old now but its good place to start.

**Comment by thomasMinshull** [comment]
K great

**Comment by Qard** [comment]
Yeah, it's out of date. Half the people on it don't even live here anymore. 😿

**Comment by thomasMinshull** [comment]
Is the meetup on the 16th going from 6pm-9pm or will it be earlier since it's a Saturday?

**Comment by Qard** [comment]
Noon to 5pm.

**Comment by sam-github** [comment]
Weekend afternoons are a scarce commodity for me, evenings almost any day of the week are easier. Its why I've been subscribed to this repo for ages, but never been to an event. Maybe mixing the times up a bit would get some more people.

**Comment by Qard** [comment]
Yep, that's something I want to start looking into. We'll probably have a session at Node.js Interactive though, so I'll probably see you there. 😎

**Comment by sam-github** [comment]
yep, I'll be there, travel approval was easy :-)

**Comment by thomasMinshull** [comment]
Jed Piezas has volunteered to be a mentor for the 16th, since I'm not going to make it I'll tell him to come talk to you Stephen, if that's ok

**Comment by thomasMinshull** [comment]
Hey guy's Just wanted to bump the thread as see if there is anything we need for Saturday. I didn't get much of a response for mentors, but I have one new person Jed Piezas. Do we have the door volunteers sorted out?

**Comment by ruxandrafed** [comment]
@thomasMinshull I will be there (downstairs) and can let people in and guide them (I work for Telus Digital, so I have an access card). We can potentially have someone else outside of the elevators. I can print some guiding signs on Friday.

How are we doing with attendance so far? How many do we expect?

**Comment by thomasMinshull** [comment]
I think signs are a great Idea :)
I think turnout might be down. I've seen Stephen tweeting a bunch 👍, but I dropped the ball on getting an announcement in the LHL email, (sorry guys). 
My guess would be 10-15

**Comment by ruxandrafed** [comment]
Hmmm, I also tweeted (personal account + Women Who Code YVR account + asked my colleagues who manage our Telus Digital account to retweet what Stephen tweeted). 

@Qard, can you see the numbers in ti.to? 😁

**Comment by Qard** [comment]
We're at 9 right now. Usually get most RSVPs in the last day or so though, so who knows where it'll really end up.

**Comment by ruxandrafed** [comment]
Hmm, well that's low. But we'll be fine anyway! Thanks for letting us know ☺️

**Comment by forivall** [comment]
I hopefully will RSVP for mentoring "in the last day or so", not sure about my saturday plans rn

**Comment by evscott** [comment]
Hi all, what level of programming experience/familiarity with node should one be coming into this nearing event with (Sept 16th)? Just RSVP'd

**Comment by Qard** [comment]
Any level is fine. There are several different workshops you can try, depending on your familiarity with JS and Node.js.

We get some people with prior experience using Node.js and some people with no tech background whatsoever. All are welcome! 😎

**Comment by evscott** [comment]
Awesome, really looking forward to the event! 👨‍💻

**Comment by ruxandrafed** [comment]
@Qard Can you meet in the lobby at 11:30AM? 😃

**Comment by Qard** [comment]
Yep. 👌

**Comment by gyaresu** [comment]
I will definitely be there tomorrow. Can meet also at 11:30 @ruxandrafed and hold doors/point at elevators. See you then?

**Comment by ruxandrafed** [comment]
Hey @gyaresu! Sounds good! See you all tomorrow 😄
