### ISSUE TITLE
October Nodeschool 2017

### ISSUE THREAD

**Issue by gyaresu** [nodeschool/vancouver#57]
Good morning @Qard and any other folks interested in organising the next meetup.

Shall we begin?
![bitmoji](https://render.bitstrips.com/v2/cpanel/9754242-322108779_2-s4-v1.png?transparent=1&palette=1&width=246)

- Venue
  - [ ] Confirm venue
  - [ ] Food provided?
  - [ ] Drinks provided?
- [ ] Make the event live for "tickets" on ti.to
 - [ ] Look into embedding ti.to tickets into https://nodeschool.io/vancouver
- [ ] Share regularly on Twitter
- [ ] Make a Facebook event
- Reach out to relevant orgs
  - [ ] Ladies Learning Code
  - [ ] Women Who Code https://twitter.com/womenwhocode

**Comment by nated0g** [comment]
I have never attended, but would like to attend the next one.  I'm also interested in volunteering for the event in whatever way I can (as long as I still get time to hang out and code!)

What about MakerLabs as a venue?
http://www.makerlabs.com/bookings/#policy

**Comment by Qard** [comment]
There's a NodeSchool coming up on October 4th as part of Node.js Interactive. Do we want to get another one rolling for later in the month or early November?

**Comment by evscott** [comment]
Is there a link available for the event on the 4th? I'm not able to locate it on the webpage.

**Comment by Qard** [comment]
There's no ticket page for it as it's part of Node.js Interactive.

**Comment by evscott** [comment]
Ah, I see. I'm up for lending a hand to getting another event going for later in the month considering not everyone will likely be able to attend the Interactive event. Has anyone reached out about a venue yet? If not, I could take on that task.

**Comment by ruxandrafed** [comment]
I'm happy to help in November. Unfortunately, I can't help during NodeJS Interactive 'cause my company got me the ticket and I want to make the most of it!

**Comment by JimFung** [comment]
So are we going to be having another october event or should we start planning for november? If we need a venue, my company is down to open up our space.

**Comment by nated0g** [comment]
I'd be interested in attending an event this month.

**Comment by Qard** [comment]
If there's a venue, I'm happy to do an October event. I contacted the Telus folks about a November event, but don't have anything solid for that yet.

**Comment by JimFung** [comment]
Yeah let's do it, let me know what dates y'all are thinking of. The space is on the 8th floor of 609 Granville, and can comfortably fit up to ~25 people, but we have capacity to go beyond that if we get a huge turnout.

**Comment by thomasMinshull** [comment]
I'm happy to help with an Oct Meet up, I guess the 28th is the most likely date, if we want to do a Saturday. Does that work for people

**Comment by Rob-Rychs** [comment]
first time nodeschool attendee here but the 28th gets my vote

**Comment by Qard** [comment]
As long as there's a venue available, that works for me. I haven't heard back from the Telus folks.

@JimFung Does your space work for the 28th?

**Comment by JimFung** [comment]
@Qard Yep! the 28th works is perfect!

**Comment by thomasMinshull** [comment]
@JimFung Time frame 12-6? also what's the address?

**Comment by JimFung** [comment]
The address is 609 Granville st. Unit 800, and noon to 6 is perfect.

So some background info. The elevator is a bit confusing to use since you have to select the floor first on a separate panel that is positioned away from the elevators and then go to the assigned elevator. 

I also think the founders (We're a startup working in the healthcare space) are willing to sponsor for pizza.

**Comment by wingkeileung** [comment]
Hi,

I recently graduated from coding school, I did JS, npm, node JS and some other JS framework while I'm in school. I don't think I am good enough to be a mentor yet (life long student here), but I wonder if I can swing by and maybe helping out my friend (or help others) as she will be joining node school for JS and node JS workshop on the 28th. And please let me know if I need a ticket as a student or so.

**Comment by Qard** [comment]
Yep, you can definitely come. The ticket is not really important, we just have the RSVPs so we have some idea how many people will show up. 👌

**Comment by thomasMinshull** [comment]
Hi @wingkeileung, welcome,

It'd be great if you'd come by. Tickets are free you can get them [here](https://ti.to/nodeschool-vancouver/2017-10-28)

**Comment by wingkeileung** [comment]
Awesome! Thank you, @Qard, @thomasMinshull !

I will see you all tomorrow! :)

**Comment by keywordnew** [comment]
This too has passed, can this be closed?
