### ISSUE TITLE
Call for mentors for NodeSchool at Node.js Interactive

### ISSUE THREAD

**Issue by Qard** [nodeschool/vancouver#58]
We're planning a NodeSchool on Wednesday, October 4th at Node.js Interactive. If you are around at the time, we could use your help mentoring!

We expect students and mentors to come and go between talks, so you can have a look at the [agenda](http://events.linuxfoundation.org/events/node-interactive/program/agenda) to find times you expect to be available.

Planned workshops:
- javascripting (all day)
- learnyounode (all day)
- how-to-npm (morning)
- stream-adventure (afternoon)

If you are interested in helping out, please leave a comment with available times.

- @qard (10am-12:50pm, 2:20pm-4:10pm)
- @gyaresu (?:?? - ?:??)
- @chowdhurian (?:?? - ?:??)

**Comment by darcyclarke** [comment]
👍 I will be there and available to help out :)

**Comment by keywordnew** [comment]
🙌  I'll be there! (9:20am-12:50pm, 2:20pm-4:40pm)

**Comment by gyaresu** [comment]
I filled out the NodeSchool Emcee Assignments and will be there the whole day.
I've also signed up online for the ticket. 
Do you think I need to do anything else @Qard?

**Comment by Qard** [comment]
Did you get the email about the pre-conf emcee meeting? Other than that, you should be all good. 👌

**Comment by gyaresu** [comment]
Yup, got it.
8-8:30am Wednesday 4th.

**Comment by ivanetchart** [comment]
Not sure if too late, but i can be around Wednesday 4th from 9am to 10am and Thursday 5th from 2:15 to 2:40pm!

**Comment by Qard** [comment]
Nope, not too late. Walk-ins are fine too. 👌

**Comment by keywordnew** [comment]
As this event has passed, can we close this?

**Comment by Qard** [comment]
Yep.
