### ISSUE TITLE
Examples of other nodeschool pages

### ISSUE THREAD

**Issue by bmann** [nodeschool/vancouver#6]
- http://nodeschool.io/dallas/ -- uses Meetup
- http://nodeschool.io/seattle/ -- also Meetup
- http://nodeschool.io/berlin/ -- Tito for events (which I guess we used, too)
- http://nodeschool.io/hamburg/ -- Tito (and a certain type of layout that would work well for us)
- http://nodeschool.io/sanfrancisco/ -- similar layout, love how they take a picture of each event / class of students
- http://nodeschool.io/austin/ -- meetup, individual events, pretty simple. Has a little bit of JS that pulls from Meetup, which seems like the best way to go

I'll fiddle a bit and see where I get to. We definitely need our own Hexdex #2 !

**Comment by lvivier** [comment]
@bmann we used [Tito](https://ti.to/) instead of Meetup because of their "you build the community but we own it" policy…I think @sintaxi wants to move Node Brigade away from Meetup as well.

**Comment by bmann** [comment]
Closing this for now, I'm going to open issues with some suggested features / tasks.
