### ISSUE TITLE
Workshopper meetup

### ISSUE THREAD

**Issue by nated0g** [nodeschool/vancouver#63]
Last Saturday at the October meetup @gyaresu suggested a more regular meetup for those interested in hacking on some of the workshoppers, and there seemed to be a good amount of interest in that.  I am definitely interested.  I thought I'd try to keep the ball rolling.

Does anyone have suggestions for a location?  A coffee shop with a decent sized booth?  Someone suggested booking a room at a library?  What days/times are good for people?  I'm pretty open most evenings except Wednesdays.

**Comment by rcass** [comment]
@nated0g Unsure if this is helpful or not, but we have some space at RED Academy if you want. 

Depending on when and the size of the group we could prob find some space for everyone. Just let me know if you are interested!

**Comment by nated0g** [comment]
@rcass that sounds great, I'll bring it up at the next monthly meet up and see how much interest there is.

**Comment by evscott** [comment]
Hey peeps, just wondering, has the ball started rolling on getting a meetup for this month or the next? If not or if so, anything I can do to help the process?

**Comment by keywordnew** [comment]
A new meetup has been announced #69

**Comment by keywordnew** [comment]
There are confirmed dates for the next few sessions [here](https://github.com/nodeschool/vancouver/blob/master/SCHEDULING.md)!

Closing this issue for now; feel free to reopen this issue or a new one to get more sessions going! 🙌🏽
