### ISSUE TITLE
Streamlining NodeSchoolYVR community communication

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/vancouver#64]
**Communication is important.**

- Participants need to know about the next workshops, or discuss past workshop topics and conversations

- Participants sometimes discuss the exercises ("workshoppers") online

- Often we need to share time-critical stuff (like how to get into our venues, or any time changes)

- Participants sometimes suggest events they'd like to see, which would be great to have if we can provide them with logistical support!

**Our current channels for communication are:**

- right here (github repo issues)

- Gitter (https://gitter.im/nodeschool/vancouver)

- replies to Twitter handle (https://twitter.com/nodeschoolyvr)

- messages/comments on our new Meetup.com page (https://www.meetup.com/nodeschool-vancouver/).

We do respond on Meetup.com, but it's not easy for everyone to carry on a conversation on there. Github issues are very useful but not conversational. Twitter would be better, but not everyone uses Twitter. Gitter is convenient (because of Github signin), but their app is glitchy. I'm not aware of others' experience with it, but it doesn't always notify me when new posts happen, so I miss requests 🙈

I'm proposing that we commit to supporting communication, response time prioritized by tiers. And to fill the user gap of Twitter, we can use a channel in a Slack team called WeAllJS (https://wealljs.org/). I've created one #nodeschool-yvr. If we want to use it, I'll make it public.

Tier 1: Twitter, Slack. (within 1 day, real-time on workshop days)
Tier 2: Meetup, Github issues. (within 2-3 days)
Tier 3: Gitter (7 days. Slowly phase out)

Thoughts? :)

**Comment by daffl** [comment]
There is also the [YVRDev Slack channel](https://yvrdev.herokuapp.com/) ([yvrdev.slack.com](https://yvrdev.slack.com)) which already has a lot of members (~2200 at the moment) from the Vancouver area.

**Comment by Qard** [comment]
Yeah, I think yvrdev might make more sense for a local group. Overall though, this all sounds good. We really haven't been great about keeping activity up in Gitter, so it's probably best to officially phase that out. As for github, I think we could do better than 2-3 days response here, but I think it's best we keep this repo for planning and meta issues. We could always create another repo in https://github.com/vancouver, if we want to.

**Comment by keywordnew** [comment]
It's official! We'll phase out Gitter.

Good idea, YVRDev is def more appropriate for this local group.

So the action items are:
1. Update our README (https://github.com/nodeschool/vancouver) to show the response time _and_ intended purpose (such as Github being for planning and meta issues) of each comm channel.
2. Update the meetup group with the same
3. Update the site (https://nodeschool.io/vancouver/) with the same.
4. While we're at it, update the site with a link to the new meetup group.

**Comment by keywordnew** [comment]
I can take care of this :) 👆🏽

**Comment by keywordnew** [comment]
fixed by https://github.com/nodeschool/vancouver/pull/65
