### ISSUE TITLE
Announcement: NodeSchool happening on April 15th + call for mentors

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/vancouver#69]
Hello y'all!

The next NodeSchool YVR will be nested in [Conf & Coffee 2018](https://www.conf.coffee/), the new 2-day conference hosted by the same people who do [Code & Coffee YVR](https://www.meetup.com/codecoffeeyvr/)!

This issue is an announcement and a call for mentors. Code & Coffee will provide us with a limited number of tickets for mentors 💯

## Details
Details can be found on the meetup event [here](https://www.meetup.com/nodeschool-vancouver/events/249169477/).

## What mentoring involves
* Being available during the 10am to 12pm workshop on Sunday April 15th
* Being a supportive mentor
* Helping setup Node.js on participant's laptops
* Helping troubleshoot

If you'd like to volunteer, reply below! Looking forward to seeing all you Node peeps again 💯

**Comment by halkeye** [comment]
This can be closed now

**Comment by keywordnew** [comment]
Thanks @halkeye! - closing 👍🏽
