### ISSUE TITLE
Document location ideas

### ISSUE THREAD

**Issue by halkeye** [nodeschool/vancouver#70]
We've recently found a bunch of nice locations to use for future events. Right now they are only in our random members heads, and in slack, and the yvrdev slack has a history limit.

Lets find somewhere better to store this information. Maybe activate the wiki section of this repo?

**Comment by keywordnew** [comment]
Storing this information is a great idea.

I feel a markdown doc would be more visible. But I may speaking more for myself as I tend to see wikis go neglected. I'd welcome using any tool that people would know to check.

We could of course link to the wiki from the readme.

**Comment by Qard** [comment]
This info might also be better suited to landing somewhere in gastown gang.

**Comment by keywordnew** [comment]
Closing this issue for now, but feel free to reopen this or a new issue for new locations and/or discussions! 💯
