### ISSUE TITLE
We should remove the `gh-pages` branch to keep from confusing new contributors

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/vancouver#74]
The gh-pages branch was originally used as the website. Now the website is sourced at `vancouver/docs/index.html`. I think it's confusing to have that branch for anyone new who wants to PR to update the website.

**Comment by halkeye** [comment]
:+1:

**Comment by halkeye** [comment]
wait, why did i 👍 this
if you don't update the gh-branch, then https://nodeschool.io/vancouver/ doesn't get updated. Its a special branch to make github pages work.

at least I think thats how it works.

**Comment by halkeye** [comment]
huh nope, how does it work

**Comment by halkeye** [comment]
OOH! i didn't know github pages offered to support a directory instead of a branch. Thats really good to know.

yea, back to 👍 for deleting the old branch

**Comment by keywordnew** [comment]
Branch deleted! Closing for now.
