### ISSUE TITLE
Incorrect date for November in SCHEDULING.md

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/vancouver#75]
The date for the meetup in November is incorrect. It should be changed to the 17th!

The relevant file is: https://github.com/nodeschool/vancouver/blob/master/SCHEDULING.md

**Comment by keywordnew** [comment]
When the file is corrected with a PR, I'll contact our venue partner.

**Comment by halkeye** [comment]
Lets hold off till we chat this weekend?

**Comment by keywordnew** [comment]
Sure!

**Comment by keywordnew** [comment]
Closed as this was resolved 😄
