### ISSUE TITLE
There's an error that needs correcting on the NodeSchool Vancouver site

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/vancouver#81]
To correct it, you can find the files in:
https://github.com/nodeschool/vancouver/tree/master/docs

<img width="431" alt="screen shot 2018-10-20 at 2 48 08 pm" src="https://user-images.githubusercontent.com/10335475/47260820-3f1f1b00-d477-11e8-9391-7bfd17452649.png">

Happy to help review your pull request or answer questions! ✨

**Comment by elskhn** [comment]
Fixed in #82 :grinning:

**Comment by keywordnew** [comment]
Thanks for the fix @abdullah-K!!! ❤️

We're happy to help guide you if you want to grab any other issue now or in future!

**Comment by elskhn** [comment]
Sure thing, @chowdhurian

I love NodeSchool and I'll definitely keep an eye out for any other issues!
