### ISSUE TITLE
2019 Venues!

### ISSUE THREAD

**Issue by halkeye** [nodeschool/vancouver#85]
Issue for tracking Venue ideas/info/etc. I'll try to keep the top level comment the summary.

| Venue | Interested | Confirmed | Location | Owner |
| ------- | ------- | ----------- |  ---- | ----- | 
| Clio | yes | no | Burnaby - North | @halkeye  |
| Sauce Labs | yes | no | Vancouver - Gastown | @halkeye / @vrunoa   |
| airG | yes | no | Vancouver - ??? | @halkeye / @nfg |

**Comment by halkeye** [comment]
* Clio has shown interest in hosting again next year, I can follow up with Ainsley again

**Comment by halkeye** [comment]
I'm guessing saucelabs would be interested, but @vrunoa would have to confirm

**Comment by halkeye** [comment]
@nfg idly suggested airg might be interested in the new year, needs to confirm if he's interested and they have space.

**Comment by halkeye** [comment]
WeWork apparently is meetup friendly, which might be a really great venue downtown, there's one outside waterfront station.

https://help.meetup.com/hc/en-us/articles/360004656412-What-is-Meetups-WeWork-

**Comment by vrunoa** [comment]
@halkeye SauceLabs would be interested in continue having NodeSchool at our HQ. Not in December since I'm going back home for the Holidays, but we'll happy to have more meetings next year.

**Comment by halkeye** [comment]
> Not in December since I'm going back home for the Holidays

Yea this is prep for next year

**Comment by Qard** [comment]
Just wanted to point out that we should probably mention in the initial post what areas are in-scope. ie: surrey, new west, richmond, etc.

**Comment by nfg** [comment]
> @nfg idly suggested airg might be interested in the new year, needs to confirm if he's interested and they have space.

I asked, and got this in reply:

> For sure!
> 
> Just need to pre-approve the organization/dates and all that jazz. So send your requests in.

I'm willing to give this a shot sometime. We have three tables in the kitchen / lounge area. We could probably bring in another table or two for more seating room. We should be able to fit twenty people, I think.

**Comment by halkeye** [comment]
Looks like wework can only do tuesday and wed, and its the smaller rooms

![image](https://user-images.githubusercontent.com/110087/48725179-32115b00-ebe0-11e8-8861-eaff34e89410.png)

So they are out for us.

**Comment by keywordnew** [comment]
Pre-approved Meetups now have access to the WeWork on Seymour.

_Gratis_. 

Can confirm NodeSchoolYVR has it now too 💁🏽

<img width="753" alt="screen shot 2018-11-19 at 8 29 04 pm" src="https://user-images.githubusercontent.com/10335475/48751543-c8259f80-ec39-11e8-8374-de58de7b41bf.png">

**Comment by halkeye** [comment]
@chowdhurian I literally said that, and clicked through to the available rooms in the previous message :)

Looks like they only have 2 rooms, super small, 2 days a week, so I don't think it'll work out for us.

**Comment by keywordnew** [comment]
@halkeye Oh my bad!!! 🙏🏽 I didn't see that stage. Understood the screenshot as a room booking done through a personal WeWork account.

Yeah, looks like it won't fit NodeSchool's needs.

**Comment by keywordnew** [comment]
Would love to hear if there are any updates on the venues @vrunoa @nfg!
