### ISSUE TITLE
Next NodeSchool event

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#9]
NodeSchool International Day (#1) was a big success. Let's keep the momentum and start planning the next event.
## Event Details

**[NodeBots Day 2015](https://github.com/nodebots/nodebotsday)**

Saturday, July 25th 12-4pm

> Zillow
> # 460 - 1122 Mainland St
> 
> Vancouver

_Edit: updated with details from thread_

**Comment by kennethormandy** [comment]
I will definitely have the logo #2 illustration done before then, so we could order some stickers and give them away to attendees or something.

**Comment by bmann** [comment]
:+1:

**Comment by Qard** [comment]
:+1: I'm happy to mentor again. :)

**Comment by gyaresu** [comment]
@Qard You were a champion of the `learnyounode` table. Every time I looked you were teaching awesome things for the whole 4 hours.

That kind of behaviour can only be suitably punished by invitations to mentor at all future events.

You're doomed.

**Comment by Qard** [comment]
It sounds like a very pleasant doom. I accept my fate.

**Comment by gyaresu** [comment]
@Qard Nice :)

So @lvivier are you married to the 5:30 - 8:30 timeslot? 

I only ask because some folks may be exhausted after work?

I 'get' how summer weekends might be a hard sell though :)

**Comment by Qard** [comment]
I would actually suggest sticking to weekends and doing a slightly longer time slot. 4 hours is kind of short. Perhaps a 6 hour slot like 10AM-4PM, with a lunch break in the middle would work well? It leaves their evening open for fun, and it gives them a good block of time to learn that somewhat coincides with the time they are used to spending at work on other days.

**Comment by gyaresu** [comment]
@Qard I agree. There was a good bit towards the end where folks were in their flow. Gave me some time to work on understanding streams as well. 

But I'm not driving this bus so very happy to go with the consensus.

edit: To note that our hosts have a pretty big say in what times/dates the event is run :)

**Comment by lvivier** [comment]
Weekends is fine too. I thought midweek might be an easier sell during the summer since ppl will want to be out on those precious sunny Saturdays. But we could tentatively say **Saturday July 11th, 10:00am-4:00pm**.

**Comment by Qard** [comment]
Wednesday nights also never work for me, so there's a bit of selfish desire to not have it on that day. It's probably fine once, but I couldn't do that regularly.

Maybe we should do send out a poll with some suggested dates/times?

**Comment by jfmaggie** [comment]
Look forward to weekend events here. @lvivier Saturday July 11th sounds fine. I will volunteer to help.

**Comment by amatecha** [comment]
Wednesdays are good for me.  But I'd just be a lowly attendee, not a mentor.  ;)

**Comment by superkhau** [comment]
Wednesdays do not work for me either.

**Comment by bmann** [comment]
I think summer is going to be an anomaly in general.

And even then, you'll get a certain type of people OK giving up weekends, and a different segment OK with evenings. I'd suggest we have more frequent, shorter, after work events, and then longer, infrequent weekend events.

Code & Coffee are every month and have "about" an hour to do some side project coding -- that's the kind of stuff I would welcome for weekday evenings where I could tinker with some personal code, get a second pair of eyes, etc. Or someone could make it through one or two of the learnnode exercises, and continue on their own.

If you guys want to do something in July, should lock it in and announce.

**Comment by gyaresu** [comment]
@bmann Sounds like a plan. 

Something like:
- Evenings
  - 2hrs(?)
  - More frequent: every 4-6 weeks
- Weekends
  - 6hrs(?)
  - Less frequent: every 2 months

**Comment by gyaresu** [comment]
And we're back. :)

Hi everyone!

So are we still thinking of next Saturday 11th July @lvivier ? Because that works for me.

Other thoughts:
[International Nodebot Day](https://github.com/nodebots/nodebotsday) is 25th July 2015

I would like to get a bunch of robot gadgets and play with them next weekend. Thoughts? Where's the best place to get that stuff in Van?
Is there already someone playing with node and bots?
Anyone interested?
If so should we co-ordinate gadget purchases in another issue?
Is this too hackerspace? Do we need benches and soldering boards?

**personal note**:
I'm going to Makerlabs friday night to meetup with the inventors of Keyboardio http://blog.keyboard.io/ 
I've backed and am really excited about this keyboard and also the Roost laptop stand.
https://www.kickstarter.com/projects/86285180/roost-laptop-stand-free-yourself-from-laptop-neck

**Comment by Qard** [comment]
Saturday might be hard for people travelling back from CascadiaFest, if it starts early. Timing it with nodebots day might be good. We should try to commit to running it at a set interval though so it doesn't start to lag like other events. Something like "The last x day of every y month" would be good for consistency.

**Comment by gyaresu** [comment]
@Qard I like the idea of consistency. 

I definitely feel like there could be a more venn diagram style overlap between groups like Node Brigade, NodeSchool, Nodebots and other hacker/coder groups.

Also perhaps a better way to co-ordinate calendars.

**Comment by gyaresu** [comment]
[Nodebot Workshop](https://github.com/tableflip/nodebot-workshop)

![Nodebot workshop menu](https://raw.githubusercontent.com/tableflip/nodebot-workshop/master/screenshot.png)

Learn the basics of the [johnny-five](https://github.com/rwaldron/johnny-five) api, as a series of code challenges.

[johnny-five](https://github.com/rwaldron/johnny-five) is an api for working with Arduino and other rapid prototyping boards.

**You _don't_ need an Arduino for this workshop.**

The workshop will pose a challenge, and will test your code.

The low level code to talk to the Arduino is stubbed out.

**You _will_ be writing working, executable johnny-five code.**

Each of your solutions can be run directly as a `node` program.

Wire up an Arduino, connect the USB and you can see your solution run for real.

**Comment by lrlna** [comment]
Saturday is a little short notice. I think giving people at least two weeks to schedule would probably be best. Also, yes, Cascadia.js checkout is 11th ^.^

**Comment by lvivier** [comment]
@gyaresu 25th looks good, I'm pro-Nodebots. I'm out of town but let's plan it out on Monday?

**Comment by gyaresu** [comment]
:+1: Sounds good. Have a lovely weekend!

**Comment by Qard** [comment]
The first night of Celebration of Light is on the 25th, so it might be good to use that as an excuse for people to come downtown early.

**Comment by gyaresu** [comment]
:neckbeard: + :thought_balloon: 

I **really** enjoyed the last NodeSchool get-together (thanks again @lvivier)

The main highlight for me was that we got a diverse crowd in areas such as gender and experience. I'd love to do even better this time. (Parent+kid combos?)

In that spirit I think it would be great if we can target the areas that will appeal to the greatest range of participants.

**On a personal note**: There are bugs and updates that need to be done to some of the NodeSchool workshops. There's also some things I'd like to understand about callbacks and properties they have.

i.e. Within the `nodebot-workshop` they use callbacks in a way that does not directly pass the return data as a parameter.

``` javascript
sensor.on('data', function () {
  console.log(this.value)
})
// rather than
sensor.on('data', function (data) {
  console.log(data.value)
})
```

_Maybe we might think about having an advanced group who look into adopting a workshop? Something for us to pull apart and give some love?_

## NodeSchool with a NodeBots theme

[International Nodebots Day 25th July](https://github.com/nodebots/nodebotsday)

[NodeSchool Workshoper List](http://nodeschool.io/#workshopper-list)

### Beginner workshops
- [javascripting](https://github.com/sethvincent/javascripting)
- [scope-chains-closures](https://github.com/jesstelford/scope-chains-closures)
- Introduction to REPL?

### Intermediate workshops
- [learnyounode](https://github.com/workshopper/learnyounode)
- [count-to-6](https://github.com/domenic/count-to-6)
- [tower-of-babel](https://github.com/yosuke-furukawa/tower-of-babel)
- Events and the event loop? https://www.youtube.com/watch?v=8aGhZQkoFbQ

### Nodebot specific
- [nodebot-workshop](https://github.com/tableflip/nodebot-workshop)
- [Arduino Experimenter's Guide for NodeJS](http://node-ardx.org) [Recommended]

Below is a picture of my [Solarbotics Arduino Experimentors Kit (ARDX)](https://solarbotics.com/product/ardx/). I got next day delivery ($101.94)

![img_1103](https://cloud.githubusercontent.com/assets/29263/8685222/1e9af478-2a32-11e5-89fa-bb8d349cea4a.JPG)

**Comment by kriscooke** [comment]
:scream_cat: This is awesome, can't wait. Noticed this shortly after pre-ordering my Tessel 2!

**Comment by lvivier** [comment]
@gyaresu this looks really cool! Thanks for doing all the work of assembling these resources. I think I can round up a Tessel and a Spark Core as well. Do you want to do this at Zillow again? I'll confirm the office and we can set up an event on Tito today and start promoting!

**Comment by gyaresu** [comment]
@kriscooke I ordered a [Tessel2](https://tessel.io/) also. Next time we can be Tessel buddies :)
_(What's a Tessel2? It's like a cross between a Raspberry Pi and an Arduino. It has the I/O pins for hooking up to sensors etc. but it also runs Javascript/Python/Rust natively so you can use it like a server and controller)_

@lvivier I think it would be great to do it at Zillow again. And promoting it as soon as possible would be the best.

In terms of hardware I think it's fine to focus on the `node` more than the `bots`. Even having a few working Arduino's there to confirm working code might be enough.

There's always the option to put together some minimal Arduino's made from breadboards and Atmel Atmega8/168/328 AVR microcontrollers.
- [Building an Arduino on a Breadboard](https://www.arduino.cc/en/main/standalone) [arduino.cc]
- [1-Day Project: Build Your Own Arduino Uno for $5 ](https://www.youtube.com/watch?v=sNIMCdVOHOM) [Video]

The more opinions the better right now. **So if you're lurking, please share your thoughts!**

**Comment by jfmaggie** [comment]
Is it okay I bring my raspberry pi there? Even though i haven't set up any dev environment yet. :grin:

**Comment by Qard** [comment]
Certainly. :)

I have an RPi2 of my own to bring, with a bunch of extra hardware and tools.

**Comment by gyaresu** [comment]
@jfmaggie @Qard As the Raspberry Pi is a full computer just without peripherals like mouse/keyboard/screen or wifi it can certainly be used to host a node server to drive an arduino but that might be a level higher than just coding straight against the `johnny-five` library using `node` from a laptop.

What do you think? 

If there's something you'd like to do with the Pi specifically then it might be something worth planning for and making a section of the room with cables and hdmi enabled monitors etc.

I just worry that it may be going too far into the 'Install and configure Linux' territory which is a different set of skills.

If there's the interest though then I definitely don't want to stifle creativity :)

Especially if you have a defined goal. Such as _'How to configure and run node from a Raspberry Pi for great success.'_

(note: I hope I'm coming across as questioning and supportive rather than negative)

**Comment by Qard** [comment]
Nope, all are good points.

RPi _does_ have gpio pins though, so you _can_ do robot stuff with them, if you have Linux already configured. Arduino is definitely more straight-forward though. The need for peripherals does certainly make RPi likely to be a bit troublesome.

**Comment by lvivier** [comment]
@gyaresu we're good to go for the location, I set up an event on Tito, if you want to edit the description (Admin > Customize > Homepage) and put it live, go for it! We'll get the word out today.

It looks like the NodeBots Day repo has some organizational stuff going on as well, do you want to take point on that? Or should we just do our own thing?

**Comment by gyaresu** [comment]
Sorry for the delay. 
I'll customize and go live with the event as well as getting our event on the [International Nodebots Day](https://github.com/nodebots/nodebotsday) page.

**Comment by gyaresu** [comment]
@lvivier I don't think I've got admin on the page you created. I can see the page but not able to get to `admin`.

**Comment by gyaresu** [comment]
And we're live: https://ti.to/nodeschool-vancouver/2015-07-25

**Comment by gyaresu** [comment]
So let's get in early for the next NodeSchool meetup.

## Saturday 29th ~~July~~ August?

Ti.to is good for tickets but we need a (no-reply) notification email list. A way for folks to subscribe and unsubscribe to future events.

Conversations should happen here and Gitter.im I think.

**Comment by Qard** [comment]
I assume you mean August?

Also, yes. More events!
