### ISSUE TITLE
NodeSchool at the Richmond Public Library

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/vancouver#97]
As part of the initiative #96, with regular events in Burnaby, Richmond was the next region to support :)

Richmond Public Library is open to hosting on some or all of the following dates that we have in our [schedule](https://github.com/nodeschool/vancouver/blob/master/SCHEDULING.md):

June 8, Aug 10, Sept 14, Oct 12

Which days would we like to schedule there?

**Comment by Qard** [comment]
I'm good with any of those.

**Comment by keywordnew** [comment]
But, are you good with _all_ of those? ;)

**Comment by halkeye** [comment]
Do we have to commit to multiple?

I vote sooner rather than later, June 8th.

**Comment by keywordnew** [comment]
We don't have to commit to multiple; one is perfectly fine.

+1 to June 8th 👍🏽

**Comment by halkeye** [comment]
Cool, that just leaves me to find a venue for April

**Comment by halkeye** [comment]
I mean may
